#!/bin/bash
source config

# sets options
for i in "$@"; do
    case $i in
        *)
        STORY_ID=$1
        ;;
    esac
done

if [ -z $STORY_ID ]; then
    echo $NO_STORY_ID
    exit 1
fi

# gets files
STORY_ID_PATTERN="$PREFIX_STORY_ID$STORY_ID$STORY_ID_END_PATTERN"
FILES=$(git log --pretty=%n --name-only --grep=$STORY_ID_PATTERN)

# sorts and prints files 
while IFS='' read -ra ADDR; do
    for file in "${ADDR[@]}"; do
        FILE_ARRAY+=($file)
    done
done <<< "$FILES"

IFS=$'\n' SORTED=($(sort -u <<<"${FILE_ARRAY[*]}"))
unset IFS

for file in "${SORTED[@]}"; do
    echo $file
done
